"use strict";

// One entry per Rust target triple this repo builds in
// .github/workflows/release.yml (see `targets` in dist-workspace.toml). Each
// entry names the release archive `dist` attaches to the GitHub Release for
// that target, and the path to the `salvor` binary once it is unpacked.
//
// This list is hand-maintained in step with dist-workspace.toml's `targets`.
// It used to be generated by cargo-dist into the npm package it built; now
// that this package is repo-owned (see npm/salvor-cli/README-internal.md),
// keeping the two lists in sync is a manual release-time check.
const supportedPlatforms = {
  "aarch64-apple-darwin": {
    artifactName: "salvor-cli-aarch64-apple-darwin.tar.xz",
    bin: "salvor",
  },
  "aarch64-unknown-linux-gnu": {
    artifactName: "salvor-cli-aarch64-unknown-linux-gnu.tar.xz",
    bin: "salvor",
  },
  "aarch64-unknown-linux-musl-dynamic": {
    artifactName: "salvor-cli-aarch64-unknown-linux-musl.tar.xz",
    bin: "salvor",
  },
  "aarch64-unknown-linux-musl-static": {
    artifactName: "salvor-cli-aarch64-unknown-linux-musl.tar.xz",
    bin: "salvor",
  },
  "x86_64-apple-darwin": {
    artifactName: "salvor-cli-x86_64-apple-darwin.tar.xz",
    bin: "salvor",
  },
  "x86_64-pc-windows-msvc": {
    artifactName: "salvor-cli-x86_64-pc-windows-msvc.zip",
    bin: "salvor.exe",
  },
  "aarch64-pc-windows-msvc": {
    // No native arm64 Windows build ships (see dist-workspace.toml's
    // `targets`); arm64 Windows runs the x64 binary under emulation, same
    // fallback the shell/powershell installers use.
    artifactName: "salvor-cli-x86_64-pc-windows-msvc.zip",
    bin: "salvor.exe",
  },
  "x86_64-unknown-linux-gnu": {
    artifactName: "salvor-cli-x86_64-unknown-linux-gnu.tar.xz",
    bin: "salvor",
  },
  "x86_64-unknown-linux-musl-dynamic": {
    artifactName: "salvor-cli-x86_64-unknown-linux-musl.tar.xz",
    bin: "salvor",
  },
  "x86_64-unknown-linux-musl-static": {
    artifactName: "salvor-cli-x86_64-unknown-linux-musl.tar.xz",
    bin: "salvor",
  },
};

// The glibc version the Linux gnu targets are built against (ubuntu-22.04
// runners in release.yml). A host with an older glibc, or a non-glibc libc,
// falls back to the statically linked musl build.
const glibcMinimum = { major: 2, series: 35 };

function error(msg) {
  console.error(msg);
  process.exit(1);
}

function getTargetTriple() {
  const libc = require("detect-libc");
  const rawOsType = require("os").type();
  const rawArchitecture = require("os").arch();

  let osType = "";
  switch (rawOsType) {
    case "Windows_NT":
      osType = "pc-windows-msvc";
      break;
    case "Darwin":
      osType = "apple-darwin";
      break;
    case "Linux":
      osType = "unknown-linux-gnu";
      break;
  }

  let arch = "";
  switch (rawArchitecture) {
    case "x64":
      arch = "x86_64";
      break;
    case "arm64":
      arch = "aarch64";
      break;
  }

  if (rawOsType === "Linux") {
    if (libc.familySync() === "musl") {
      osType = "unknown-linux-musl-dynamic";
    } else if (libc.isNonGlibcLinuxSync()) {
      console.warn(
        "Your libc is neither glibc nor musl; trying the static musl binary instead",
      );
      osType = "unknown-linux-musl-static";
    } else {
      const [libcMajor, libcMinor] = libc.versionSync().split(".");
      if (
        libcMajor !== String(glibcMinimum.major) ||
        Number(libcMinor) < glibcMinimum.series
      ) {
        console.warn(
          "Your glibc isn't compatible; trying the static musl binary instead",
        );
        osType = "unknown-linux-musl-static";
      }
    }
  }

  return `${arch}-${osType}`;
}

function getPlatform() {
  const targetTriple = getTargetTriple();
  const platform = supportedPlatforms[targetTriple];
  if (!platform) {
    error(
      `salvor: no prebuilt binary for "${require("os").type()}" / "${require("os").arch()}".\nSupported targets:\n\n${Object.keys(
        supportedPlatforms,
      ).join(", ")}`,
    );
  }
  return platform;
}

module.exports = { supportedPlatforms, getPlatform };
